# Generated by Django 3.1.1 on 2020-09-15 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='date of birth',
            new_name='date_of_birth',
        ),
    ]
